// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZPg0HnQZMGMSrtDuUdEkr5Nb04XTt-3c',
    appId: '1:166898504450:web:8de8f7a5de1db0d442a81b',
    messagingSenderId: '166898504450',
    projectId: 'petpal-db',
    authDomain: 'petpal-db.firebaseapp.com',
    storageBucket: 'petpal-db.appspot.com',
    measurementId: 'G-LTE4H30JNB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL4jjb2tvvrqsb7586ZfMFeF8eCgS16do',
    appId: '1:166898504450:android:1a25b8b3159597d342a81b',
    messagingSenderId: '166898504450',
    projectId: 'petpal-db',
    storageBucket: 'petpal-db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm1jPkm59MRePpPhSmEAYc66pH5KTDFag',
    appId: '1:166898504450:ios:c7088319f46bad7842a81b',
    messagingSenderId: '166898504450',
    projectId: 'petpal-db',
    storageBucket: 'petpal-db.appspot.com',
    iosBundleId: 'com.example.petpalapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm1jPkm59MRePpPhSmEAYc66pH5KTDFag',
    appId: '1:166898504450:ios:687f2667c14aecff42a81b',
    messagingSenderId: '166898504450',
    projectId: 'petpal-db',
    storageBucket: 'petpal-db.appspot.com',
    iosBundleId: 'com.example.petpalapp.RunnerTests',
  );
}
